package com.kauanferreira.smartdaojdbc.entity;

import java.io.Serial;
import java.io.Serializable;
import java.util.Objects;

/**
 * Represents a department entity mapped to the database.
 * Implements {@link Serializable} to allow object serialization.
 *
 * <p>Equality is based solely on the {@code id} field,
 * following the database primary key convention.</p>
 *
 * @author Kauan
 * @version 1.0
 * @since 2026
 */

public class Department implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    /** Unique identifier generated by the database. */
    private Integer id;

    /** Department name. */
    private String name;

    /**
     * Default no-args constructor required for frameworks and serialization.
     */
    public Department() {
    }

    /**
     * Creates a new Department with the specified id and name.
     *
     * @param id   the department identifier
     * @param name the department name
     */
    public Department(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    /**
     * Returns the department identifier.
     *
     * @return the department id, or {@code null} if not yet persisted
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the department identifier.
     *
     * @param id the department id, must be greater than zero
     * @throws IllegalArgumentException if id is null or less than 1
     */
    public void setId(Integer id) {
        if (id == null || id < 1) {
            throw new IllegalArgumentException("Id must be greater than zero");
        }
        this.id = id;
    }

    /**
     * Returns the department name.
     *
     * @return the department name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the department name.
     *
     * @param name the department name, must not be null or blank
     * @throws IllegalArgumentException if name is null or empty
     */
    public void setName(String name) {
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException("Department name cannot be empty");
        }
        this.name = name;
    }

    /**
     * Compares this department with another object for equality.
     * Two departments are equal if they share the same {@code id}.
     *
     * @param o the object to compare with
     * @return {@code true} if the objects are equal, {@code false} otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Department that = (Department) o;
        return Objects.equals(id, that.id);
    }

    /**
     * Returns the hash code based on the department {@code id}.
     *
     * @return the hash code value
     */
    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    /**
     * Returns a formatted string representation of this department.
     *
     * @return string containing id and name
     */
    @Override
    public String toString() {
        return String.format("Department = | id = %d | name = %s |", id, name);
    }
}
