package com.kauanferreira.smartdaojdbc.entity;

import java.io.Serial;
import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

/**
 * Represents a seller entity mapped to the database.
 * Implements {@link Serializable} to allow object serialization.
 *
 * <p>Each seller is associated with a {@link Department}.
 * Equality is based solely on the {@code id} field,
 * following the database primary key convention.</p>
 *
 * @author Kauan
 * @version 1.0
 * @since 2026
 */
public class Seller implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    /** Unique identifier generated by the database. */
    private Integer id;

    /** Seller's full name. */
    private String name;

    /** Seller's email address. */
    private String email;

    /** Seller's date of birth. */
    private Date birthDate;

    /** Seller's base salary. */
    private Double baseSalary;

    /** Department to which the seller belongs. */
    private Department department;

    /**
     * Default no-args constructor required for frameworks and serialization.
     */
    public Seller() {
    }

    /**
     * Creates a new Seller with the specified attributes.
     *
     * @param id         the seller identifier
     * @param name       the seller's full name
     * @param email      the seller's email address
     * @param baseSalary the seller's base salary
     * @param birthDate  the seller's date of birth
     * @param department the department associated with this seller
     */
    public Seller(Integer id, String name, String email, Double baseSalary, Date birthDate, Department department) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.baseSalary = baseSalary;
        this.birthDate = birthDate;
        this.department = department;
    }

    /**
     * Returns the seller identifier.
     *
     * @return the seller id, or {@code null} if not yet persisted
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the seller identifier.
     *
     * @param id the seller id, must be greater than zero
     * @throws IllegalArgumentException if id is null or less than 1
     */
    public void setId(Integer id) {
        if (id == null || id < 1) {
            throw new IllegalArgumentException("Id must be greater than zero");
        }
        this.id = id;
    }

    /**
     * Returns the seller's full name.
     *
     * @return the seller name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the seller's full name.
     *
     * @param name the seller name, must not be null or blank
     * @throws IllegalArgumentException if name is null or empty
     */
    public void setName(String name) {
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException("Name cannot be null or empty");
        }
        this.name = name;
    }

    /**
     * Returns the seller's email address.
     *
     * @return the seller email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the seller's email address.
     *
     * @param email the seller email, must not be null or blank
     * @throws IllegalArgumentException if email is null or empty
     */
    public void setEmail(String email) {
        if (email == null || email.trim().isEmpty()) {
            throw new IllegalArgumentException("Email cannot be null or empty");
        }
        if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
            throw new IllegalArgumentException("Invalid email format");
        }
        this.email = email;
    }

    /**
     * Returns the seller's date of birth.
     *
     * @return the birth date
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the seller's date of birth.
     *
     * @param birthDate the seller's date of birth
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * Returns the seller's base salary.
     *
     * @return the base salary
     */
    public Double getBaseSalary() {
        return baseSalary;
    }

    /**
     * Sets the seller's base salary.
     *
     * @param baseSalary the base salary, must not be negative
     * @throws IllegalArgumentException if baseSalary is null or negative
     */
    public void setBaseSalary(Double baseSalary) {
        if (baseSalary != null && baseSalary < 0) {
            throw new IllegalArgumentException("Base salary cannot be negative");
        }
        this.baseSalary = baseSalary;
    }

    /**
     * Returns the department associated with this seller.
     *
     * @return the department
     */
    public Department getDepartment() {
        return department;
    }

    /**
     * Sets the department associated with this seller.
     *
     * @param department the department to associate
     */
    public void setDepartment(Department department) {
        this.department = department;
    }

    /**
     * Compares this seller with another object for equality.
     * Two sellers are equal if they share the same {@code id}.
     *
     * @param o the object to compare with
     * @return {@code true} if the objects are equal, {@code false} otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Seller seller = (Seller) o;
        return Objects.equals(id, seller.id);
    }

    /**
     * Returns the hash code based on the seller {@code id}.
     *
     * @return the hash code value
     */
    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    /**
     * Returns a formatted string representation of this seller.
     *
     * @return string containing all seller attributes
     */
    @Override
    public String toString() {
        return String.format(
                "Seller = | Id = %d | Name = %s | Email = %s | BirthDate = %s | BaseSalary = %.2f | Department: %s ",
                id, name, email, birthDate, baseSalary, department
        );
    }
}